// List of 100+ Greek architect and builder names for naming construction creeps and entities
const builderArchitectNames = [
    "Ictinus", "Callicrates", "Mnesicles", "Phidias", "Libon of Elis", "Pythius of Priene", 
    "Satyros", "Anthemius of Tralles", "Isidore of Miletus", "Hermogenes of Priene", 
    "Chersiphron", "Metagenes", "Rhoecus", "Theodorus of Samos", "Eupalinos of Megara", 
    "Scopas", "Paeonius of Ephesus", "Daphnis of Miletus", "Cossutius", "Philon of Eleusis", 
    "Polykleitos the Younger", "Dinocrates of Rhodes", "Andronicus of Cyrrhus", 
    "Sostratus of Cnidus", "Hippodamus of Miletus", "Agamedes", "Trophonius", "Gitiadas of Sparta", 
    "Bathycles of Magnesia", "Archias of Corinth"
];

// List of 100+ Greek diplomat and envoy names for naming diplomatic creeps and entities
const diplomatEnvoyNames = [
    "Themistocles", "Aristides", "Cimon", "Pericles", "Callias", 
    "Alcibiades", "Nicias", "Archidamus II", "Tissaphernes (Greek-allied satrap)", 
    "Antalcidas", "Pelopidas", "Epaminondas", "Philocrates", "Demosthenes", 
    "Aeschines", "Phocion", "Aristodemus of Metapontum", "Hegesippus", 
    "Pytho of Byzantium", "Dinarchus", "Hyperides", "Craterus", "Demades", 
    "Xenocrates", "Callistratus", "Polybius", "Aratus of Sicyon", "Critolaus", 
    "Carneades", "Diogenes of Babylon", "Astyochus", "Theramenes", "Lysander", 
    "Xenophon", "Agesilaus II", "Cineas", "Gorgias of Leontini", "Tisias"
];

// List of 100+ Greek healer and doctor names for naming medical creeps and entities
const healerDoctorNames = [
    "Asclepius", "Hippocrates", "Galen", "Dioscorides", "Herophilus", "Erasistratus", 
    "Alcmaeon of Croton", "Apollonius of Tyana", "Aretaeus of Cappadocia", "Rufus of Ephesus", 
    "Soranus of Ephesus", "Paul of Aegina", "Alexander of Tralles", "Oribasius", 
    "Philistion of Locri", "Dexippus of Cos", "Draco (son of Hippocrates)", "Thessalus (son of Hippocrates)", 
    "Polybus", "Praxagoras of Cos", "Chrysippus of Cnidus", "Heraclides of Tarentum", 
    "Archagathus", "Xenophon of Cos", "Erasistratus of Ceos", "Nicander of Colophon", 
    "Ctesias of Cnidus", "Acron of Agrigentum", "Menecrates of Syracuse", "Eryximachus", 
    "Antyllus", "Heliodorus", "Philumenus", "Archigenes", "Democedes of Croton"
 ];

// List of 100+ Greek mythological figures for naming creeps, power creeps, and other entities
const pantheonNames = [
    "Chaos", "Gaia", "Uranus", "Cronus", "Rhea", 
    "Oceanus", "Tethys", "Hyperion", "Theia", 
    "Coeus", "Phoebe", "Iapetus", "Themis", 
    "Mnemosyne", "Crius", "Atlas", "Prometheus", 
    "Epimetheus", "Zeus", "Hera", "Poseidon", 
    "Demeter", "Athena", "Apollo", "Artemis", 
    "Ares", "Aphrodite", "Hephaestus", "Hermes", 
    "Hestia", "Dionysus", "Hades", "Persephone", 
    "Pan", "Hecate", "Eros", "Hebe", "Iris", 
    "Eris", "Helios", "Selene", "Eos", "Leto", 
    "Maia", "Dione", "Metis", "Tyche", "Nemesis", 
    "Nike", "Zelus", "Bia", "Kratos", "Phobos", 
    "Deimos", "Harmonia", "Ganymede", "Asclepius", 
    "Hygieia", "Panacea", "Morpheus", "Hypnos", 
    "Thanatos", "Charon", "Nyx", "Erebus", "Hemera", 
    "Aether", "Tartarus", "Pontus", "Thalassa", 
    "Nereus", "Doris", "Amphitrite", "Triton", "Proteus", 
    "Glaucus", "Ino", "Melicertes", "Phorcys", "Ceto", 
    "Eurybia", "Styx", "Nike", "Aphros", "Bythos", 
    "Astraeus", "Pallas", "Perses", "Asteria", "Lelantos", 
    "Ananke", "Chronos", "Phanes", "Thesis", "Physis", 
    "Nesoi", "Ourea", "Thalassa", "Actaeon", "Adonis", 
    "Aeolus", "Agdistis", "Alastor", "Amphiaraus", "Angelos", 
    "Aristaeus", "Astraea", "Atropos", "Clotho", "Lachesis", 
    "Boreas", "Zephyrus", "Notus", "Eurus", "Calliope", 
    "Clio", "Erato", "Euterpe", "Melpomene", "Polyhymnia", 
    "Terpsichore", "Thalia", "Urania", "Aglaia", "Euphrosyne", "Thalia"
];

// List of 100+ Greek city-states (poleis) for naming rooms and other entities
const poleisNames = [
    "Athens", "Sparta", "Corinth", "Thebes", "Argos", "Delphi", 
    "Olympia", "Megara", "Aegina", "Eretria", "Chalcis", "Mycenae", 
    "Epidaurus", "Troezen", "Hermione", "Mantinea", "Tegea", 
    "Messene", "Elis", "Patras", "Sicyon", "Orchomenos", "Plataea", 
    "Tanagra", "Chaeronea", "Marathon", "Eleusis", "Piraeus", 
    "Sunion", "Laurion", "Carystus", "Styra", "Amarynthos", 
    "Lefkandi", "Knossos", "Gortyn", "Phaistos", "Cydonia", 
    "Itanos", "Rhodes", "Lindos", "Ialysos", "Cameirus", "Cos", 
    "Samos", "Chios", "Mytilene", "Methymna", "Eresos", "Byzantium", 
    "Chalcedon", "Heraclea Pontica", "Sinope", "Trapezus", "Cyzicus", 
    "Lampsacus", "Abydos", "Sestos", "Troy", "Miletus", "Ephesus", 
    "Erythrae", "Clazomenae", "Phocaea", "Smyrna", "Colophon", "Priene", 
    "Myus", "Magnesia", "Halicarnassus", "Cnidus", "Phaselis", 
    "Side", "Aspendos", "Perge", "Tarsus", "Soli", "Salamis", 
    "Kition", "Paphos", "Kurion", "Amathus", "Cyrene", "Barca", "Apollonia", 
    "Euhesperides", "Taucheira", "Syracuse", "Akragas", "Gela", 
    "Selinus", "Himera", "Segesta", "Catania", "Messina", "Rhegium", 
    "Croton", "Sybaris", "Thurii", "Metapontum", "Tarentum", "Locri", 
    "Cumae", "Neapolis", "Poseidonia", "Elea", "Massalia", "Emporion", 
    "Kypsela", "Abdera", "Maroneia", "Aenus", "Thasos", "Samothrace", "Lemnos", 
    "Imbros", "Skyros", "Delos", "Naxos", "Paros", "Melos", "Thera", "Ios", 
    "Amorgos", "Siphnos", "Seriphos", "Kythnos", "Kea", "Andros", "Tenos", "Mykonos"
];

// List of 100+ Pre-Socratic philosophers for naming philosophical creeps and entities
const philosophersNames = [
    "Thales", "Anaximander", "Anaximenes", "Pythagoras", "Heraclitus", "Parmenides", 
    "Zeno of Elea", "Empedocles", "Anaxagoras", "Democritus", "Leucippus", "Protagoras", 
    "Gorgias", "Prodicus", "Hippias", "Socrates", "Plato", "Aristotle", "Xenophon", 
    "Antisthenes", "Diogenes of Sinope", "Crates of Thebes", "Aristippus", "Epicurus", 
    "Metrodorus", "Hermarchus", "Zeno of Citium", "Cleanthes", "Chrysippus", "Carneades", 
    "Arcesilaus", "Pyrrho", "Timon", "Panaetius", "Posidonius", "Epictetus", "Marcus Aurelius", 
    "Seneca", "Plotinus", "Porphyry", "Iamblichus", "Proclus", "Hypatia", "Philolaus", "Archytas", 
    "Alcmaeon", "Melissus", "Xenophanes", "Critias", "Thrasymachus", "Crito", "Phaedo", 
    "Speusippus", "Xenocrates", "Polemon", "Crates of Athens", "Aristo of Chios", "Herillus", 
    "Dionysius the Renegade", "Persaeus", "Menedemus", "Monimus", "Onesicritus", "Metrocles", 
    "Hipparchia", "Arete of Cyrene", "Hegesias", "Anniceris", "Theodorus the Atheist", 
    "Strato of Lampsacus", "Lyco of Troas", "Aristo of Ceos", "Critolaus", "Diodorus of Tyre", 
    "Apollodorus", "Philo of Larissa", "Antiochus of Ascalon", "Aenesidemus", "Agrippa the Skeptic", 
    "Sextus Empiricus", "Plutarch", "Maximus of Tyre", "Albinus", "Atticus", "Numenius", "Ammonius Saccas"
];

// List of 100+ Greek scientists for naming scientific creeps and entities
const scientistsMathmaticianNames = [
    "Thales of Miletus", "Pythagoras", "Euclid", "Archimedes", "Eratosthenes", "Aristarchus of Samos", 
    "Hipparchus", "Claudius Ptolemy", "Diophantus", "Apollonius of Perga", "Hero of Alexandria", 
    "Anaximander", "Anaxagoras", "Democritus", "Aristotle", "Eudoxus of Cnidus", "Theon of Alexandria", 
    "Hypatia", "Pappus of Alexandria", "Geminus", "Autolycus of Pitane", "Menaechmus", "Callippus", 
    "Conon of Samos", "Nicomedes", "Diocles", "Zenodorus", "Hypsicles", "Menelaus of Alexandria", 
    "Strato of Lampsacus", "Sosigenes", "Cleomedes", "Geminus", "Heliodorus of Larissa"
];

// List of 100+ Greek military generals for naming military creeps and entities
const militaryNames = [
    "Achilles", "Agamemnon", "Ajax the Great", "Diomedes", "Odysseus", "Menelaus", "Nestor", "Patroclus", 
    "Leonidas I", "Pausanias", "Miltiades", "Themistocles", "Aristides", "Cimon", "Pericles", "Cleon", 
    "Brasidas", "Gylippus", "Lysander", "Agesilaus II", "Pelopidas", "Epaminondas", "Iphicrates", 
    "Xenophon", "Philip II of Macedon", "Alexander the Great", "Parmenion", "Hephaestion", 
    "Seleucus I Nicator", "Ptolemy I Soter", "Antigonus I Monophthalmus", "Lysimachus", "Craterus", 
    "Cassander", "Eumenes of Cardia", "Pyrrhus of Epirus", "Philopoemen", "Aratus of Sicyon", 
    "Nabis", "Demetrius Poliorcetes", "Xanthippus of Carthage", "Dion of Syracuse", "Timoleon", 
    "Agathocles", "Pyrrhus", "Cleomenes III", "Xanthippus", "Memnon of Rhodes", "Aristodemus", "Dienekes", 
    "Leon of Byzantium", "Chabrias", "Phocion", "Leosthenes"
];

// List of ~1000 generic Greek names for naming creeps and other entities
const genericNames = [
    "Aaron", "Abantidas", "Abydos", "Acacia", "Acacius", "Acantha", "Acanthos", "Acaste", "Acaustus", 
    "Achaios", "Achelous", "Achillia", "Achlyos", "Acis", "Acontius", "Adamos", "Adara", "Adonia", "Adonios", 
    "Adrasteia", "Adrastos", "Adriana", "Adrias", "Adros", "Aegle", "Aegon", "Aeidion", "Aelia", "Aelius", 
    "Aemilia", "Aemilios", "Aeneas", "Aenon", "Aeschines", "Aesculapius", "Aeson", "Aesop", "Aetes", "Aethra", 
    "Agapi", "Agapios", "Agapius", "Agasicles", "Agasthenes", "Agathon", "Agathocles", "Agathoklis", "Agathos", 
    "Agathosta", "Agave", "Agelaos", "Agenor", "Agis", "Aglaia", "Aglaope", "Aglaos", "Aglauros", "Agnodice", 
    "Agreus", "Agrios", "Agrotas", "Aiakos", "Aias", "Aidas", "Aidoios", "Aigeus", "Aigina", "Aigisthos", "Aigyptos", 
    "Aimon", "Aineas", "Aiolos", "Aison", "Aithon", "Aithra", "Akastos", "Akrisios", "Aktaion", "Akylos", "Alastor", 
    "Alcaeus", "Alcestis", "Alcia", "Alcippos", "Alcmene", "Alcon", "Alcyone", "Aleca", "Alec", "Alekto", "Alenas", 
    "Aleria", "Alessa", "Alethea", "Aletheia", "Aleuas", "Alexandros", "Alexandra", "Alexia", "Alexias", "Alexina", 
    "Alexios", "Alexis", "Alexius", "Alexon", "Alkaios", "Alkestis", "Alkippe", "Alkmaeon", "Alkman", "Alkyone", 
    "Alkyon", "Alpheios", "Alpheus", "Althaea", "Amalthea", "Amara", "Amarantos", "Amaryllis", "Amarynthia", 
    "Ambrosia", "Ambrosios", "Ammianos", "Ammon", "Amorgos", "Amphiaraus", "Amphion", "Amphitryon", "Amykos", 
    "Amyntas", "Amyntor", "Anacharsis", "Anacleto", "Anactoria", "Anais", "Ananias", "Anastas", "Anastasia", 
    "Anastasios", "Anastasius", "Anax", "Anaxagoras", "Anaxarchos", "Anaxias", "Anaxilaos", "Anaximandros", 
    "Anaximenis", "Anaxippos", "Anaxo", "Anchises", "Andreas", "Andreia", "Andro", "Androcles", "Androklis", 
    "Andromache", "Andromeda", "Andron", "Andronicus", "Andros", "Anemos", "Anemone", "Angelos", "Angela", 
    "Angelica", "Angeliki", "Angelos", "Anicetus", "Aniketos", "Anis", "Anna", "Annas", "Antaeus", 
    "Antenor", "Anteros", "Anthe", "Anthea", "Anthos", "Anthoula", "Anticlea", "Antigone", "Antigonos", 
    "Antigonus", "Antilochos", "Antilochus", "Antinoos", "Antinous", "Antiochos", "Antiochus", "Antiope", 
    "Antonios", "Antonis", "Anyte", "Apelles", "Aphthonios", "Apollodoros", "Apollonios", "Apollonius", 
    "Apollos", "Arachne", "Aratus", "Arcadius", "Arcadis", "Arcas", "Arcesilaos", "Archelaos", "Archias", 
    "Archidamos", "Archilochos", "Archon", "Archytas", "Arete", "Arethusa", "Aretos", "Argeios", "Argeus", 
    "Argiros", "Argus", "Ariadne", "Ariana", "Ariane", "Arion", "Aris", "Aristaeus", "Aristarchos", "Aristarchus", 
    "Aristides", "Aristion", "Aristippos", "Aristobulus", "Aristocles", "Aristocritus", "Aristodemos", "Aristogeiton", 
    "Aristomache", "Aristomenes", "Ariston", "Aristophanes", "Aristoxenus", "Arkas", "Arktos", "Arsen", "Arsenia", 
    "Arsenios", "Arsenius", "Artas", "Artemas", "Artemia", "Artemisias", "Artemidorus", "Artemios", "Artemisia", "Artemon", 
    "Ascalaphos", "Asclepios", "Asopus", "Aspasia", "Aspasios", "Astakas", "Aster", "Asteria", "Asterion", "Asterios", 
    "Asteris", "Astra", "Astraea", "Astraeus", "Astyanax", "Atalanta", "Athamas", "Athanas", "Athanasia", "Athanasios", 
    "Athenagoras", "Athenais", "Athenodorus", "Atlas", "Atreus", "Attis", "Augeas", "Augos", "Augustus", 
    "Autolycus", "Automedon", "Autonoe", "Auxesia", "Babis", "Babys", "Bacchylides", "Bacchus", "Bakchos", 
    "Barys", "Basile", "Basileia", "Basileios", "Basileus", "Basil", "Bassos", "Battos", "Baukis", "Bellerophon", "Belus", 
    "Bendis", "Berenice", "Berniki", "Bia", "Bias", "Biton", "Boethus", "Bolbe", "Boreas", "Branchus", "Briseis", 
    "Britomartis", "Brizo", "Bromios", "Brygos", "Butes", "Byblos", "Byzas", "Cadmus", "Caeneus", "Calais", "Calchas", "Callia", 
    "Callias", "Callicles", "Callicrates", "Callidora", "Callimachos", "Calliope", "Callirrhoe", "Callista", "Callistenes", 
    "Callisto", "Calypso", "Canace", "Capaneus", "Carme", "Cassandra", "Cassandros", "Cassia", "Cassiopeia", "Castor", "Cecrops", 
    "Celeus", "Celeustas", "Cephalos", "Cepheus", "Cephisodotus", "Cephissus", "Cerberus", "Cercyon", "Ceryx", "Ceto", "Ceyx", 
    "Chares", "Chariclides", "Charilaos", "Charis", "Chariton", "Charon", "Charybdis", "Cheiron", "Chilon", "Chion", "Chione", 
    "Chios", "Chloe", "Chloris", "Chremes", "Chrysa", "Chrysaor", "Chryseis", "Chryses", "Chrysippos", "Chrysogonos", 
    "Chrysos", "Chrysostomos", "Chrysothemis", "Chthon", "Cimon", "Circe", "Clea", "Cleanthes", "Cleisthenes", "Cleitus", 
    "Cleon", "Cleopatra", "Cleopas", "Clio", "Clotho", "Clymene", "Clytemnestra", "Clytius", "Codrus", "Coeus", "Colotes", 
    "Conon", "Cora", "Corinna", "Coroebus", "Corybantes", "Corydus", "Cottus", "Cranaus", "Crates", "Creon", "Cresphontes", 
    "Cretheus", "Creusa", "Crius", "Critias", "Crito", "Critobulus", "Critolaus", "Croesus", "Cronus", "Ctesias", 
    "Ctesibius", "Ctesippus", "Cyane", "Cyaxares", "Cybele", "Cycnus", "Cylon", "Cyparissus", "Cypria", "Cypselus", "Cyrene", 
    "Cyrus", "Cytherea", "Cytisorus", "Cyzicus", "Daedalus", "Daemon", "Damaris", "Damascas", "Damascius", "Damaskinos", 
    "Damaso", "Damia", "Damianos", "Damianus", "Damion", "Damocles", "Damodar", "Damon", "Danae", "Danaos", "Danaus", 
    "Daphnaea", "Daphne", "Daphnis", "Dardanus", "Dares", "Deianira", "Deidameia", "Deimos", "Deinocrates", "Deinomachos", 
    "Deiphobe", "Deiphobus", "Deipyle", "Delia", "Delias", "Delon", "Demades", "Demaratus", "Demeter", "Demetria", 
    "Demetrios", "Demetrius", "Democedes", "Democritus", "Demodocus", "Demophon", "Demosthenes", "Despina", "Deucalion", 
    "Dexileos", "Diagoras", "Diana", "Dicaearchus", "Dictys", "Didymus", "Dike", "Dinarchus", "Dinocrates", "Dinomachus", 
    "Diodorus", "Diogenes", "Diomedes", "Dione", "Dionysia", "Dionysios", "Dionysius", "Diophantus", "Diotima", "Diphilus", 
    "Dirca", "Doris", "Doros", "Dorothea", "Dorotheos", "Dorotheus", "Dorus", "Doryphoros", "Dracon", "Dryas", "Dryope", 
    "Dysnomia", "Echecrates", "Echetus", "Echidna", "Echion", "Echo", "Eileithyia", "Eirene", "Elara", "Elatos", "Electra", 
    "Eleonora", "Eleos", "Eleutheria", "Eleutherios", "Eleusis", "Elpenor", "Elpis", "Elymus", "Empedocles", "Enceladus", 
    "Endymion", "Enipeus", "Ennomos", "Enyo", "Eos", "Epaphus", "Epeius", "Ephialtes", "Epicharmos", "Epictetus", 
    "Epicurus", "Epigoni", "Epimenides", "Epimetheus", "Epione", "Epiphanius", "Eratosthenes", "Erato", "Erebus", 
    "Erechtheus", "Erginus", "Erichthonius", "Erigone", "Erinyes", "Eriphyle", "Eris", "Eros", "Erymanthus", "Erysichthon", 
    "Eryx", "Eteocles", "Eteoclus", "Eubuleus", "Eubulus", "Euclides", "Euclion", "Eudamidas", "Eudora", "Eudoxos", 
    "Euemerus", "Eugamon", "Eumaeus", "Eumelus", "Eumenes", "Eumolpos", "Eunomia", "Eunomos", "Euphorbus", "Euphorion", 
    "Euphranor", "Euphrosyne", "Eupolis", "Euripides", "Europa", "Eurotas", "Eurus", "Euryalos", "Eurybatos", "Eurybia", 
    "Eurybiades", "Eurycleia", "Eurydice", "Eurylochos", "Eurymachos", "Eurymedon", "Eurynome", "Eurypylus", "Eurysaces", 
    "Eurysthenes", "Eurystheus", "Eurytos", "Euterpe", "Euthydemos", "Euthymios", "Euthymius", "Eutropius", "Evadne", 
    "Evagoras", "Evan", "Evander", "Evenus", "Evgenia", "Exarchos", "Exekias", "Gaia", "Galatea", "Galen", "Galene", 
    "Gallos", "Ganymede", "Geras", "Geryon", "Glauce", "Glaucias", "Glaucon", "Glaucus", "Glykera", "Glykon", "Gorgias", 
    "Gorgon", "Gortys", "Graces", "Gyes", "Gyges", "Haemon", "Hagias", "Halcyone", "Halirrhothius", "Hannas", "Harmonia", 
    "Harpalus", "Harpies", "Hebe", "Hecate", "Hecatoncheires", "Hector", "Hecuba", "Hegesias", "Hegesinus", "Hegesippus", 
    "Hegesistratus", "Helena", "Helenos", "Helia", "Helios", "Hellas", "Helle", "Hellen", "Helos", "Hemera", "Hephaestion", 
    "Hera", "Herakles", "Heraclides", "Heraclitus", "Heras", "Herillus", "Hermaios", "Hermaphroditus", "Hermione", 
    "Hermippus", "Hermocrates", "Hermogenes", "Hermolaus", "Hermotimus", "Hero", "Herodes", "Herodianus", "Herodorus", 
    "Herodotus", "Herophile", "Herostratus", "Hesiod", "Hesione", "Hesperos", "Hestia", "Hetoemocles", "Hicetas", "Hiero", 
    "Hieronymos", "Hilaeira", "Hilas", "Himera", "Himeros", "Hipparchia", "Hipparchus", "Hipparinus", "Hippias", "Hippo", 
    "Hippocoon", "Hippocrates", "Hippodamia", "Hippodamus", "Hippolyta", "Hippolytus", "Hippomachus", "Hippomedon", 
    "Hippomenes", "Hipponax", "Hipponous", "Hippothoon", "Hippothous", "Histiaeus", "Homeros", "Hyacinthia", "Hyacinthus", 
    "Hyades", "Hybris", "Hydna", "Hydra", "Hygieia", "Hylas", "Hyllos", "Hymen", "Hyperbolus", "Hyperides", "Hyperion", 
    "Hypermnestra", "Hypsipyle", "Hyrcanus", "Hyrtacus", "Iacchus", "Ialmenus", "Iambe", "Iamblichus", "Ianeira", "Ianthe", 
    "Iapetus", "Iapyx", "Iarbas", "Iasion", "Iasos", "Ibycus", "Icarus", "Icelos", "Ida", "Idaeus", "Idas", "Idomeneus", 
    "Idmon", "Idomene", "Idothea", "Iero", "Ieronymos", "Ikaros", "Iktinos", "Ileus", "Iliona", "Ilioneus", "Ilos", "Immarados", 
    "Inachus", "Ino", "Io", "Iobates", "Iolaus", "Iolcos", "Iole", "Ion", "Iophon", "Iphias", "Iphicles", "Iphicrates", 
    "Iphigenia", "Iphimedeia", "Iphinoe", "Iphis", "Iphitos", "Irene", "Iris", "Irus", "Isagoras", "Isaias", "Isaeus", 
    "Ischys", "Isidoros", "Isidorus", "Isigonus", "Ision", "Ismene", "Ismenias", "Isocrates", "Istros", "Isyllus", "Itylus", 
    "Itys", "Iulus", "Ixion", "Jason", "Jocasta", "Kadmos", "Kaeneus", "Kaikas", "Kalais", "Kalanos", "Kalchas", "Kallia", 
    "Kallias", "Kallikles", "Kallikrates", "Kallinikos", "Kalliope", "Kallirrhoe", "Kallisthenes", "Kallisto", "Kalypso", 
    "Kanake", "Kapaneus", "Karme", "Kassandra", "Kassiopeia", "Kastor", "Keleustas", "Kephalos", "Kepheus", "Kerberos", 
    "Kerkyon", "Keryx", "Keto", "Keyx", "Khares", "Khariklides", "Kharon", "Kharybdis", "Kheiron", "Khilon", "Khion", "Khione", 
    "Khios", "Khloe", "Khloris", "Khremes", "Khryseis", "Khryses", "Khrysippos", "Khrysogonos", "Khrysothemis", "Khthon", 
    "Kimon", "Kirke", "Kleanthes", "Kleisthenes", "Kleitos", "Kleoboulos", "Kleomachos", "Kleomenes", "Kleon", "Kleopatra", 
    "Klio", "Klotho", "Klymene", "Klytaimnestra", "Klytios", "Kodros", "Koios", "Kolotes", "Konon", "Korinna", "Koroibos", 
    "Korydus", "Kottos", "Kranaos", "Krates", "Kreon", "Kresphontes", "Kretheus", "Kreusa", "Krios", "Kritias", "Kriton", 
    "Kritoboulos", "Kritolaos", "Kroisos", "Kronos", "Ktesias", "Ktesibios", "Ktesippos", "Kyane", "Kyaxares", "Kybele", 
    "Kyknos", "Kylon", "Kyparissos", "Kypria", "Kypselos", "Kyrene", "Kyros", "Kythereia", "Kytisorus", "Kyzikos", 
    "Lachesis", "Lacydes", "Ladas", "Lades", "Ladon", "Laertes", "Laestrygon", "Laius", "Lamia", "Lampedo", "Lampon", 
    "Lampos", "Lampsacus", "Laocoon", "Laodamia", "Laodice", "Laomedon", "Lapithus", "Laris", "Larisa", "Larymna", "Lasus", 
    "Leander", "Learchus", "Leda", "Leipsydrion", "Leitus", "Leleges", "Lelantos", "Lemnos", "Leon", "Leonatus", "Leonidas", 
    "Leonnatus", "Leontion", "Leosthenes", "Leotychides", "Lepreus", "Lerna", "Lesbonax", "Lesches", "Leto", "Leucippus", 
    "Leucothea", "Leuctra", "Libanius", "Lichas", "Linus", "Locrus", "Loxias", "Lucian", "Lycaon", "Lyciscus", "Lyco", 
    "Lycomedes", "Lycon", "Lycophron", "Lycortas", "Lycurgus", "Lycus", "Lydos", "Lygdamis", "Lynceus", "Lysander", 
    "Lysanias", "Lysias", "Lysicles", "Lysidice", "Lysimachus", "Lysippus", "Lysistrata", "Macareus", "Machaon", 
    "Maeander", "Maenads", "Maera", "Maia", "Maneros", "Mantias", "Mantitheus", "Marathus", "Mardonius", "Maron", "Marpessa", 
    "Marsyas", "Medea", "Medon", "Medusa", "Megabyzus", "Megaera", "Megakles", "Megapenthes", "Megara", "Megas", "Megasthenes", 
    "Melampus", "Melanippe", "Melanippus", "Melanthius", "Melantho", "Melas", "Meleager", "Melete", "Meliboea", "Melicertes", 
    "Melissa", "Melissus", "Melpomene", "Memnon", "Menander", "Mende", "Mendesian", "Menecrates", "Menedemus", "Menelaus", 
    "Menestheus", "Menippus", "Menoetes", "Menoetius", "Menon", "Mentor", "Meriones", "Mermnad", "Merope", "Metabus", 
    "Metaneira", "Metion", "Metis", "Meton", "Metrodorus", "Midas", "Mikkos", "Miletus", "Milo", "Miltiades", "Mimnermus", 
    "Minos", "Minotaur", "Minthe", "Minyas", "Mnemosyne", "Mnesarchus", "Mnesicles", "Mnesilochus", "Mnesippus", 
    "Mnesitheus", "Moerocles", "Moero", "Molion", "Molossus", "Momus", "Monimus", "Mopsus", "Morpheus", "Moschion", 
    "Moschus", "Musaeus", "Muses", "Myia", "Myron", "Myrtilus", "Myrtis", "Mys", "Nausicaa", "Nausithous", "Neaira", 
    "Neanthes", "Nearchus", "Neleus", "Nemea", "Nemesis", "Neoptolemus", "Nephele", "Nereids", "Nereus", "Nessus", "Nestor", 
    "Nicander", "Nicanor", "Nicarete", "Nicephorus", "Niceratus", "Nicias", "Nicocles", "Nicomachus", "Nicomedes", "Nicon", 
    "Nicophon", "Nicostratus", "Nike", "Niobe", "Nireus", "Nisus", "Nomion", "Nonnus", "Nothon", "Notus", "Nycteus", 
    "Nyctimene", "Nyx", "Oceanids", "Oceanus", "Ocnus", "Odysseus", "Oeagrus", "Oedipus", "Oeneus", "Oenomaus", "Oenone", 
    "Oenopion", "Ogyges", "Oileus", "Olbia", "Olympia", "Olympias", "Olympiodorus", "Olympus", "Omphale", "Onomacritus", 
    "Onomarchus", "Onomastus", "Ophelas", "Ophellas", "Opheltes", "Ops", "Orchomenus", "Orestes", "Oreus", "Origen", "Orion", 
    "Orithyia", "Ormenus", "Ornytus", "Orpheus", "Orsilochus", "Orthros", "Ortygia", "Otus", "Oura", "Oxyartes", "Oxylus", 
    "Paeon", "Palamedes", "Pallas", "Pallene", "Pamphilus", "Pan", "Panacea", "Panaetius", "Panathenaea", "Pancrates", 
    "Pandareus", "Pandion", "Pandora", "Pandrosos", "Panopeus", "Panteus", "Panthea", "Panyassis", "Papias", "Paralus", 
    "Paris", "Parmenides", "Parmenion", "Parnassus", "Parnops", "Parthenia", "Parthenius", "Parthenopaeus", "Parthenope", 
    "Parysatis", "Pasiphae", "Pasithea", "Patroclus", "Pausanias", "Peisander", "Peisistratus", "Pelagon", "Peleus", 
    "Pelias", "Pelopia", "Pelopidas", "Pelops", "Penia", "Penelope", "Penthesilea", "Pentheus", "Perdix", "Periander", 
    "Periboea", "Pericles", "Periclymenus", "Perieres", "Perilaus", "Perimede", "Perimedes", "Periphas", "Periphetes", 
    "Pero", "Persephone", "Perses", "Perseus", "Phaedo", "Phaedra", "Phaedrus", "Phaethon", "Phalanthus", "Phalerus", 
    "Phanes", "Phanias", "Phanus", "Phaon", "Pharnabazus", "Pharnaces", "Phegeus", "Pheidias", "Pheidippides", "Pheidon", 
    "Phemius", "Pheneus", "Pherae", "Pherecrates", "Pherecydes", "Pheres", "Pheretima", "Phidias", "Phidippides", "Phidon", 
    "Phigalia", "Phila", "Philaon", "Philargyrus", "Phileas", "Philemon", "Philenor", "Philesius", "Philetas", "Philinna", 
    "Philip", "Philippe", "Philippides", "Philiscus", "Philistion", "Philistus", "Philo", "Philochorus", "Philocles", 
    "Philocrates", "Philoctetes", "Philodemus", "Philolaus", "Philomela", "Philomelus", "Philonides", "Philopappus", 
    "Philopoemen", "Philostephanus", "Philostratus", "Philotas", "Philotera", "Philotimus", "Philoxenus", "Philyra", 
    "Phineus", "Phintias", "Phlegethon", "Phlegyas", "Phobetor", "Phobos", "Phocas", "Phocion", "Phocus", "Phoebe", 
    "Phoebidas", "Phoebus", "Phoenix", "Pholus", "Phorcys", "Phormio", "Phoroneus", "Photius", "Phradmon", "Phrasicleia", 
    "Phrasicles", "Phrastor", "Phrixus", "Phronima", "Phryne", "Phrynichus", "Phrynon", "Phthonos", "Phycous", "Phylacus", 
    "Phylarchus", "Phyleus", "Phyllis", "Physon", "Pierus", "Pigres", "Pinacus", "Pindar", "Pionius", "Pittacus", "Pittheus", 
    "Pixodarus", "Placidas", "Planudes", "Plataea", "Plato", "Pleistarchus", "Pleistoanax", "Ploutos", "Plutarch", 
    "Pluto", "Podaleirius", "Podares", "Poeas", "Polemon", "Polites", "Pollis", "Pollux", "Polyidus", "Polybius", 
    "Polybus", "Polycaon", "Polycaste", "Polycleitus", "Polycles", "Polycritus", "Polydamas", "Polydorus", "Polyidus", 
    "Polymnestus", "Polymnia", "Polyneices", "Polyperchon", "Polyphron", "Polysperchon", "Polystratus", "Polyxena", 
    "Polyxenus", "Polyxo", "Pontus", "Porphyry", "Porthaon", "Portheus", "Porus", "Poseidippus", "Poseidon", "Posidonius", 
    "Posthumus", "Potone", "Poton", "Pratinas", "Praxagoras", "Praxias", "Praxilla", "Praxiteles", "Priam", "Priapus", 
    "Procne", "Proclus", "Procopius", "Procris", "Procrustes", "Prodicus", "Proetus", "Prometheus", "Promethos", 
    "Propertius", "Protagoras", "Protesilaus", "Proteus", "Protogenes", "Protogonus", "Proxenos", "Prusias", 
    "Prytanis", "Psammetichus", "Psaphon", "Psaon", "Psyche", "Psychro", "Pteleon", "Ptolemy", "Pylades", "Pyramus", 
    "Pyrilampes", "Pyrrha", "Pyrrho", "Pyrrhus", "Pythagoras", "Pytheas", "Pythermus", "Pytheus", "Pythius", 
    "Pythocritus", "Pythodoros", "Pytholaus", "Python", "Pythonicus", "Pythonax", "Rhadamanthys", "Rhea", "Rhesus", 
    "Rhianus", "Rhidine", "Rhinton", "Rhodope", "Rhodos", "Rhoecus", "Rhoetus", "Rhyndakos", "Sabazius", "Sacadas", 
    "Sadyattes", "Salamis", "Salmoneus", "Sappho", "Sarpedon", "Satyros", "Sciron", "Scopa", "Scylax", "Scylla", 
    "Selene", "Seleucus", "Semele", "Semonides", "Seneca", "Serapis", "Sestos", "Sibyl", "Sicyon", "Silanion", 
    "Silenus", "Simonides", "Sinon", "Sinope", "Sipylus", "Sirens", "Sisyphus", "Sitalcas", "Smaragdus", "Smerdis", 
    "Smyrna", "Socrates", "Solon", "Sophocles", "Sophron", "Sosicles", "Sosigenes", "Sosiphanes", "Sosipolis", 
    "Sosistratus", "Sosthenes", "Sostratus", "Sotades", "Soter", "Speusippus", "Sphacteria", "Sphinx", "Staphylus", 
    "Stasinus", "Statira", "Stentor", "Sterope", "Stesichorus", "Stesilaus", "Stheneboea", "Sthenelus", "Stheno", 
    "Stilpo", "Strabo", "Straticus", "Straton", "Stratonice", "Strattis", "Strymon", "Stymphalus", "Styx", 
    "Syleus", "Syphax", "Talthybius", "Tanagra", "Tantalus", "Taras", "Tartarus", "Tatis", "Tauron", "Tegea", 
    "Teisias", "Telamon", "Telegonus", "Telemachus", "Telephus", "Telesarchus", "Telesilla", "Telesphorus", 
    "Teleutias", "Telys", "Temenus", "Tenes", "Teos", "Terambus", "Terence", "Tereus", "Terpander", "Terpsichore", 
    "Tethys", "Teucer", "Teuthras", "Thais", "Thalassa", "Thales", "Thalia", "Thalysios", "Thamyris", "Thanatos", 
    "Thargelia", "Thasos", "Thaumas", "Theagenes", "Theano", "Thebe", "Theia", "Thelxinoe", "Themis", "Themista", 
    "Themistocleia", "Themistocles", "Themistogenes", "Theoclymenus", "Theocritus", "Theodore", "Theodorus", 
    "Theodosius", "Theodote", "Theodotus", "Theognis", "Theon", "Theophanes", "Theophilus", "Theophrastus", 
    "Theopompus", "Theramenes", "Theras", "Theron", "Thersander", "Thersites", "Theseus", "Thesmophoria", 
    "Thespis", "Thestius", "Thestor", "Thetis", "Thimbron", "Thisbe", "Thoas", "Thon", "Thrason", "Thrasybulus", 
    "Thrasydaios", "Thrasyllus", "Thrasymachus", "Thrasymedes", "Thucydides", "Thyestes", "Thymoetes", "Thyone", 
    "Timachidas", "Timon", "Timoclea", "Timocrates", "Timolaus", "Timoleon", "Timomachus", "Timonax", "Timotheus", 
    "Timoxenos", "Tiresias", "Tisamenus", "Tisiphone", "Tissaphernes", "Tithonus", "Tityus", "Tlepolemus", 
    "Tmolus", "Tragas", "Triton", "Triptolemus", "Troilus", "Trophonius", "Tros", "Tryphon", "Tyche", "Tydeus", 
    "Tyndareus", "Typhon", "Tyro", "Tyrtaeus", "Uranus", "Urania", "Xanthippe", "Xanthippus", "Xanthus", "Xenagoras", 
    "Xenarchus", "Xenocles", "Xenocrates", "Xenon", "Xenophanes", "Xenophon", "Xerxes", "Xuthus", "Zacynthus", 
    "Zaleucus", "Zephyr", "Zethus", "Zeuxis", "Zoilos", "Zosimus"
];

module.exports = {
    builderArchitectNames,
    diplomatEnvoyNames,
    healerDoctorNames,
    pantheonNames,
    poleisNames,
    philosophersNames,
    scientistsMathmaticianNames,
    militaryNames,
    genericNames
};